[bridge-outbound]
exten => s,1,NoOp(Iniciando flujo hacia Sarah para llamada ID: ${X_CALL_ID})
 same => n,Goto(from-internal-custom,7777,1)

[from-internal-custom]
exten => 8000,1,NoOp(Calling OpenAI SIP)
 same => n,Set(__XAST_UNIQUEID=${CHANNEL(uniqueid)})
 same => n,Set(__XAST_CHANNEL=${CHANNEL(name)})
 same => n,Dial(PJSIP/openai-endpoint,300,b(add-openai-headers^s^1))
 same => n,Hangup()

exten => 90000,1,NoOp(Escalando llamada, enviando 90000 a PBX PROD)
 same => n,Dial(PJSIP/90000@ext-remote,60)
 same => n,Hangup()

exten => 9998,1,NoOp(Llamando al Agente SilverAI en ElevenLabs)
 same => n,Set(PJSIP_SEND_SESSION_REFRESH=request)
 same => n,Set(CALLERID(num)=9998)
 same => n,Set(__X_CALL_ID=${CHANNEL})
 same => n,Set(__X_CALLER_ID=${CALLERID(num)})
 same => n,System(redis-cli -a "578R2DV926J0B1U089SGUB4GD" SETEX "phone:${CALLERID(num)}" 3600 "${CHANNEL}")
 same => n,Dial(PJSIP/elevenlabs-endpoint/sip:9997@sip.rtc.elevenlabs.io,300,b(add-elevenlabs-headers^s^1))
 same => n,Hangup()

exten => 9997,1,NoOp(Llamada de TEST - ElevenLabs)
 same => n,Set(PJSIP_SEND_SESSION_REFRESH=request)
 same => n,Set(CALLERID(num)=9997)
 same => n,Set(X_CALL_ID=${CHANNEL})
 same => n,Set(X_CALLER_ID=${CALLERID(num)})
 same => n,System(redis-cli -a "578R2DV926J0B1U089SGUB4GD" SETEX "phone:${CALLERID(num)}" 3600 "${CHANNEL}")
 same => n,Dial(PJSIP/elevenlabs-endpoint/sip:9997@sip.rtc.elevenlabs.io,300,b(add-elevenlabs-headers^s^1))
 same => n,Hangup()

exten => 9090,1,NoOp(Llamada de SarahIA - ElevenLabs)
 same => n,Set(PJSIP_SEND_SESSION_REFRESH=request)
 same => n,Set(CALLERID(num)=9090)
 same => n,Set(__X_CALL_ID=${CHANNEL})
 same => n,Set(__X_CALLER_ID=${CALLERID(num)})
 same => n,System(redis-cli -a "578R2DV926J0B1U089SGUB4GD" SETEX "phone:${CALLERID(num)}" 3600 "${CHANNEL}")
 same => n,Dial(PJSIP/SarahIA-endpoint/sip:21@sip.rtc.elevenlabs.io,300,b(add-elevenlabs-headers^s^1))
 same => n,Hangup()

exten => 7777,1,NoOp(Iniciando flujo: Humano=${DESTINO_HUMANO} ID=${X_CALL_ID})
 same => n,Set(__ID_LLAMADA=${X_CALL_ID})
 same => n,Set(__NUM_HUMANO=${DESTINO_HUMANO})
 same => n,System(redis-cli -a "578R2DV926J0B1U089SGUB4GD" -p 6380 SETEX "call_status:${ID_LLAMADA}" 3600 "DISPATCHED")
 same => n,Dial(PJSIP/${NUM_HUMANO}@ext-remote,60,G(from-internal-custom^7777^10))
 same => n,Gosub(handler-finalizar,s,1(${ID_LLAMADA}))
 same => n,Hangup()
 same => 10,NoOp(Humano contesto, conectando con Sarah...)
 same => n,System(redis-cli -a "578R2DV926J0B1U089SGUB4GD" -p 6380 SETEX "call_status:${ID_LLAMADA}" 3600 "IN_PROGRESS")
 same => n,Dial(PJSIP/SarahIA-endpoint/sip:3232@sip.rtc.elevenlabs.io,300,b(add-elevenlabs-headers^s^1(${ID_LLAMADA},${NUM_HUMANO})))
 same => n,Gosub(handler-finalizar,s,1(${ID_LLAMADA}))
 same => n,Hangup()

[handler-finalizar]
exten => s,1,NoOp(Finalizando llamada ID: ${ARG1})
 same => n,Set(ESTADO_DIAL=${DIALSTATUS})
 same => n,Set(NUEVO_STATUS=${IF($["${ESTADO_DIAL}"="ANSWER"]?COMPLETED:${IF($["${ESTADO_DIAL}"="BUSY"]?BUSY:${IF($["${ESTADO_DIAL}"="NOANSWER"]?NOANSWER:FAILED)})})})
 same => n,ExecIf($["${HANGUPCAUSE}"="16"]?Set(NUEVO_STATUS=COMPLETED))
 same => n,System(redis-cli -a "578R2DV926J0B1U089SGUB4GD" -p 6380 SETEX "call_status:${ARG1}" 3600 "${NUEVO_STATUS}")
 same => n,Return()

[add-elevenlabs-headers]
exten => s,1,NoOp(Headers ElevenLabs para ID: ${ARG1})
 same => n,Set(PJSIP_HEADER(add,X-Call-ID)=${ARG1})
 same => n,Set(PJSIP_HEADER(add,X-Caller-ID)=${ARG2})
 same => n,Return()

[add-openai-headers]
exten => s,1,NoOp(Adding OpenAI SIP headers)
 same => n,Set(PJSIP_HEADER(add,X-Ast-UniqueID)=${XAST_UNIQUEID})
 same => n,Set(PJSIP_HEADER(add,X-Ast-Channel)=${XAST_CHANNEL})
 same => n,Return()

[to_SilverAI]
exten => 9998,1,NoOp(Llamada entrante desde PBX PROD a 9998 - enviando a ElevenLabs por SIP)
 same => n,Goto(from-internal-custom,9998,1)
